name: aira
description: Aplikasi monitoring kualitas udara dan tanaman berbasis Flutter

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.1.0
  provider: ^6.0.5
  sensors_plus: ^3.0.0
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/ICON AIRA.png"

flutter:
  uses-material-design: true
  
