// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbRmGAY3PytA2MLZag8n9FbiasZVoacdY',
    appId: '1:1069296455146:web:bddfdbd5f67b1acec37693',
    messagingSenderId: '1069296455146',
    projectId: 'aira-web-app',
    authDomain: 'aira-web-app.firebaseapp.com',
    databaseURL: 'https://aira-web-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aira-web-app.firebasestorage.app',
    measurementId: 'G-H8KHT2XVFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABhnI4OHwmbBeXnvuwf1M3ZY0OqBF9rLc',
    appId: '1:1069296455146:android:67bd9b325cfa7567c37693',
    messagingSenderId: '1069296455146',
    projectId: 'aira-web-app',
    databaseURL: 'https://aira-web-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aira-web-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd_aDlPoY0a2AtRE5_Fl603WYnTZwomLQ',
    appId: '1:1069296455146:ios:cf09a19a1fac9561c37693',
    messagingSenderId: '1069296455146',
    projectId: 'aira-web-app',
    databaseURL: 'https://aira-web-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aira-web-app.firebasestorage.app',
    iosClientId: '1069296455146-cpappnsvdg560gd29k54fl4vo9u21i4u.apps.googleusercontent.com',
    iosBundleId: 'com.example.studiKasus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd_aDlPoY0a2AtRE5_Fl603WYnTZwomLQ',
    appId: '1:1069296455146:ios:cf09a19a1fac9561c37693',
    messagingSenderId: '1069296455146',
    projectId: 'aira-web-app',
    databaseURL: 'https://aira-web-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aira-web-app.firebasestorage.app',
    iosClientId: '1069296455146-cpappnsvdg560gd29k54fl4vo9u21i4u.apps.googleusercontent.com',
    iosBundleId: 'com.example.studiKasus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbRmGAY3PytA2MLZag8n9FbiasZVoacdY',
    appId: '1:1069296455146:web:358d768c9406c2a8c37693',
    messagingSenderId: '1069296455146',
    projectId: 'aira-web-app',
    authDomain: 'aira-web-app.firebaseapp.com',
    databaseURL: 'https://aira-web-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aira-web-app.firebasestorage.app',
    measurementId: 'G-8B95VEZC04',
  );
}
